services:
  - type: web
    name: finexa-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    rootDirectory: server
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
